/*
 * accessSpecifiers.h
 *
 *  Created on: Sep 3, 2020
 *      Author: root
 */

#ifndef INET_ROUTING_NLSR_PSYNC_DETAIL_ACCESSSPECIFIERS_H_
#define INET_ROUTING_NLSR_PSYNC_DETAIL_ACCESSSPECIFIERS_H_


//#include "PSync/detail/config.hpp"

#ifdef PSYNC_WITH_TESTS
#define PSYNC_VIRTUAL_WITH_TESTS virtual
#define PSYNC_PUBLIC_WITH_TESTS_ELSE_PROTECTED public
#define PSYNC_PUBLIC_WITH_TESTS_ELSE_PRIVATE public
#define PSYNC_PROTECTED_WITH_TESTS_ELSE_PRIVATE protected
#else
#define PSYNC_VIRTUAL_WITH_TESTS
#define PSYNC_PUBLIC_WITH_TESTS_ELSE_PROTECTED protected
#define PSYNC_PUBLIC_WITH_TESTS_ELSE_PRIVATE private
#define PSYNC_PROTECTED_WITH_TESTS_ELSE_PRIVATE private
#endif



#endif /* INET_ROUTING_NLSR_PSYNC_DETAIL_ACCESSSPECIFIERS_H_ */
