//
// Generated file, do not edit! Created by nedtool 5.6 from inet/applications/ICNapp/ndnFileHead.msg.
//

#ifndef __INET_NDNFILEHEAD_M_H
#define __INET_NDNFILEHEAD_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class ndnFileData;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/ProtocolTag_m.h" // import inet.common.ProtocolTag

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet/applications/ICNapp/ndnFileHead.msg:23</tt> by nedtool.
 * <pre>
 * class ndnFileData extends FieldsChunk
 * {
 *     chunkLength = B(8);
 *     double seq;
 * }
 * </pre>
 */
class INET_API ndnFileData : public ::inet::FieldsChunk
{
  protected:
    double seq = 0;

  private:
    void copy(const ndnFileData& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ndnFileData&);

  public:
    ndnFileData();
    ndnFileData(const ndnFileData& other);
    virtual ~ndnFileData();
    ndnFileData& operator=(const ndnFileData& other);
    virtual ndnFileData *dup() const override {return new ndnFileData(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getSeq() const;
    virtual void setSeq(double seq);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ndnFileData& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ndnFileData& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_NDNFILEHEAD_M_H

