//
// Generated file, do not edit! Created by nedtool 5.6 from inet/applications/compUdpApp/flowHead.msg.
//

#ifndef __INET_FLOWHEAD_M_H
#define __INET_FLOWHEAD_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class FlowReq;
class FlowData;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/ProtocolTag_m.h" // import inet.common.ProtocolTag

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet/applications/compUdpApp/flowHead.msg:26</tt> by nedtool.
 * <pre>
 * class FlowReq extends FieldsChunk
 * {
 *     int seq;
 *     chunkLength = B(8);
 *     uint32_t offset;
 * }
 * </pre>
 */
class INET_API FlowReq : public ::inet::FieldsChunk
{
  protected:
    int seq = 0;
    uint32_t offset = 0;

  private:
    void copy(const FlowReq& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FlowReq&);

  public:
    FlowReq();
    FlowReq(const FlowReq& other);
    virtual ~FlowReq();
    FlowReq& operator=(const FlowReq& other);
    virtual FlowReq *dup() const override {return new FlowReq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSeq() const;
    virtual void setSeq(int seq);
    virtual uint32_t getOffset() const;
    virtual void setOffset(uint32_t offset);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FlowReq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FlowReq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/applications/compUdpApp/flowHead.msg:33</tt> by nedtool.
 * <pre>
 * class FlowData extends FieldsChunk
 * {
 *     int seq;
 *     chunkLength = B(12);
 *     uint32_t offset;
 *     int totalLenth;
 * }
 * </pre>
 */
class INET_API FlowData : public ::inet::FieldsChunk
{
  protected:
    int seq = 0;
    uint32_t offset = 0;
    int totalLenth = 0;

  private:
    void copy(const FlowData& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FlowData&);

  public:
    FlowData();
    FlowData(const FlowData& other);
    virtual ~FlowData();
    FlowData& operator=(const FlowData& other);
    virtual FlowData *dup() const override {return new FlowData(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSeq() const;
    virtual void setSeq(int seq);
    virtual uint32_t getOffset() const;
    virtual void setOffset(uint32_t offset);
    virtual int getTotalLenth() const;
    virtual void setTotalLenth(int totalLenth);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FlowData& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FlowData& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_FLOWHEAD_M_H

