//
// Generated file, do not edit! Created by nedtool 5.6 from inet/networklayer/contract/ndn/ndnFields.msg.
//

#ifndef __INET_NDNFIELDS_M_H
#define __INET_NDNFIELDS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

// cplusplus {{
    #include <vector>
    #include <list>

    #include "inet/networklayer/contract/ndn/iName.h"
//    #include "inet/routing/nlsr/PSync/detail/iblt.h"
    using Port_t = unsigned;
//    typedef std::list<inet::iName> NIDS;
//    typedef std::vector<inet::iName> paths; // nodes name set
// }}


namespace inet {

/**
 * Enum generated from <tt>inet/networklayer/contract/ndn/ndnFields.msg:35</tt> by nedtool.
 * <pre>
 * enum TYPE
 * {
 *     INTEREST = 1;
 *     DATA = 2;
 * }
 * 
 * //class paths
 * //{
 * //    \@existingClass;
 * //}
 * //
 * //class NIDS
 * //{
 * //    \@existingClass;
 * //}
 * </pre>
 */
enum TYPE {
    INTEREST = 1,
    DATA = 2
};

} // namespace inet

#endif // ifndef __INET_NDNFIELDS_M_H

